name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3