name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NEXTAUTH_JWT_SECRET: ${{secrets.NEXTAUTH_JWT_SECRET}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          INSTRUMENT_CODE: 1
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
      - run: npm dev:instrumented
      - run: npm run cypress:run
      - run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
          flags: cypress
          name: codecov-umbrella
          fail_ci_if_error: true